version: "3.8"

services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "sos"
      DB_MYSQL_PASSWORD: "shieldOn#@25"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - phpmyadmin
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'shieldOn#@25'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'sos'
      MYSQL_PASSWORD: 'shieldOn#@25'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-nginx-proxy-manager
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

networks:
  default:
    external: true
    name: strapi_backend_internal
